version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  init-dynamodb-local:
    image: garland/aws-cli-docker
    command: sh -c
      "aws dynamodb create-table
           --table-name Pokemon
           --attribute-definitions
               AttributeName=Id,AttributeType=S
               AttributeName=Count,AttributeType=N
           --key-schema
               AttributeName=Id,KeyType=HASH
               AttributeName=Count,KeyType=RANGE
       --provisioned-throughput
           ReadCapacityUnits=10,WriteCapacityUnits=5
       --endpoint-url http://dynamodb-local:8000
       &&
       aws dynamodb create-table
           --table-name Avalara
           --attribute-definitions
               AttributeName=Id,AttributeType=S
           --key-schema
               AttributeName=Id,KeyType=HASH
       --provisioned-throughput
           ReadCapacityUnits=10,WriteCapacityUnits=5
       --endpoint-url http://dynamodb-local:8000"
    links:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_PAGER=
